apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-project-app
  labels:
    app: devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-project
  template:
    metadata:
      labels:
        app: devops-project
    spec:
      containers:
      - name: devops-project
        image: ${{ secrets.DOCKERHUB_USERNAME }}/devops-project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-project-service
spec:
  selector:
    app: devops-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
